In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import categorical_crossentropy


2022-03-17 02:18:18.452301: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-17 02:18:18.452319: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "


In [2]:
df = pd.read_csv('test.csv')
df

1    2    3  y1  y2  y3
0       3  146  -31   1   0   0
1      27  184   39   1   0   0
2      57  165   55   1   0   0
3      88   87  -10   1   0   0
4      35  165  -52   1   0   0
...   ...  ...  ...  ..  ..  ..
3079  -76 -179  125   0   0   1
3080 -198 -215  133   0   0   1
3081  -48  -95   63   0   0   1
3082 -162 -194   81   0   0   1
3083 -194   18  167   0   0   1

[3084 rows x 6 columns]

In [3]:
type(df[['2','3']].values[0][0])

numpy.int64

In [4]:
X = df[["1","2","3"]].values
#X = np.asarray(X).astype('float32')
y = df[["y1","y2","y3"]].values

x_train , x_test , y_train , y_test = train_test_split(X,y,test_size=0.2)


In [5]:
X.shape , y.shape

((3084, 3), (3084, 3))

In [6]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       ...,
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [7]:
def v_to_a (x):
    if x == 0:
        return np.array([1,0,0])
    if x == 1:
        return np.array([0,1,0])
    if x == 2:
        return np.array([0,0,1])
    

In [8]:
X

array([[   3,  146,  -31],
       [  27,  184,   39],
       [  57,  165,   55],
       ...,
       [ -48,  -95,   63],
       [-162, -194,   81],
       [-194,   18,  167]])

In [9]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)



In [10]:
a = np.array([[1,2,2]])
a[0] = v_to_a(2)
a.shape

(1, 3)

In [11]:
x_train

array([[-0.36384601, -0.93138346, -0.24577012],
       [-1.27074011,  0.43365945,  0.70313935],
       [-0.35609478, -2.00599171,  0.2516421 ],
       ...,
       [ 0.75233133, -2.27464377, -0.12333019],
       [-1.54203321,  0.17952912,  1.75918375],
       [ 0.77558503, -1.86077438,  0.2516421 ]])

In [12]:
classifier = Sequential()
classifier.add( Dense(9, kernel_initializer = 'uniform',
              activation = 'relu', input_dim=3))

classifier.add( Dense(80, kernel_initializer = 'uniform',
              activation = 'relu'))
classifier.add( Dense(100, kernel_initializer = 'uniform',
              activation = 'relu'))

classifier.add(
     Dense(3, kernel_initializer = 'uniform',
           activation = 'softmax'))

2022-03-17 02:18:21.026189: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-03-17 02:18:21.026725: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-17 02:18:21.026802: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2022-03-17 02:18:21.026869: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2022-03-17 02:18:21.026934: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

In [13]:
classifier.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 9)                 36        
                                                                 
 dense_1 (Dense)             (None, 80)                800       
                                                                 
 dense_2 (Dense)             (None, 100)               8100      
                                                                 
 dense_3 (Dense)             (None, 3)                 303       
                                                                 
Total params: 9,239
Trainable params: 9,239
Non-trainable params: 0
_________________________________________________________________


In [14]:
classifier.compile(optimizer= 'adam',
                  loss = 'categorical_crossentropy',
                  metrics = ['accuracy'])

In [15]:
x_train.shape

(2467, 3)

In [16]:
classifier.fit(x_train, y_train, batch_size = 100, epochs = 10)

Epoch 1/10
25/25 [==============================] - 1s 2ms/step - loss: 1.0915 - accuracy: 0.4694
Epoch 2/10
25/25 [==============================] - 0s 2ms/step - loss: 0.9753 - accuracy: 0.6676
Epoch 3/10
25/25 [==============================] - 0s 2ms/step - loss: 0.5880 - accuracy: 0.8123
Epoch 4/10
25/25 [==============================] - 0s 2ms/step - loss: 0.3142 - accuracy: 0.9887
Epoch 5/10
25/25 [==============================] - 0s 2ms/step - loss: 0.1060 - accuracy: 0.9907
Epoch 6/10
25/25 [==============================] - 0s 2ms/step - loss: 0.0373 - accuracy: 0.9955
Epoch 7/10
25/25 [==============================] - 0s 2ms/step - loss: 0.0223 - accuracy: 0.9955
Epoch 8/10
25/25 [==============================] - 0s 2ms/step - loss: 0.0168 - accuracy: 0.9964
Epoch 9/10
25/25 [==============================] - 0s 2ms/step - loss: 0.0134 - accuracy: 0.9959
Epoch 10/10
25/25 [==============================] - 0s 2ms/step - loss: 0.0112 - accuracy: 0.9972


In [17]:
def predict_to_array(x):
    l = len(x[0])
    for i in range (len(x)):
        a = np.zeros(l)
        
        max_i = 0
        max = x[i][0]
        j = 0
        while j < l:
            if max<x[i][j]:
                max = x[i][j]
                max_i = j
            j+=1
        a[max_i] = 1
        x[i] = a
    return x

def chek_shabih(x , y):
    if len(x)!=len(y):
        return False
    for i in range(len(x)):
        
        if x[i]!=y[i]:
            return False
    return True




In [18]:
predict_test = predict_to_array(classifier.predict(x_test))

sum = 0
for i in range(len(predict_test)):
    if chek_shabih(predict_test[i] , y_test[i]):
        sum+=1
print(sum/len(predict_test))

3
0.993517017828201


In [19]:
classifier.predict(np.array([x_test[0]])),y_test[0]



(array([[6.5133863e-05, 9.9828464e-01, 1.6501931e-03]], dtype=float32),
 array([0, 1, 0]))

In [20]:
a = np.array([[9,2,3,4,1,2],
             [1,2,3,5,2,1],
             [8,2,3,0,1,3],
             [1,7,3,2,4,3],
             [1,2,3,4,5,6]])

predict_to_array(a)

6


array([[1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1]])

In [21]:
from keras.datasets import mnist
